### PR TITLE
komodo notarisation rules (NN pubkeys and block rules) 

### PR DESCRIPTION
**Pull request by dimxy**
change zcash to komodo block future time rule
add notary pubkeys and get current season code
add 'is special block' by notary rules
allow 'second block for notary if long gap' rule
also:
rule to prevent forks staring below the last notarised height
added on 13 Jan:
komodo interest tx locktime validation

### CODE REVIEW

**Comment by dimxy** [comment]
in the latest 30 commits:
more tests fixed and enable for komodo 
in transaction.rs call for last bloc time is not done for coinbase

**Comment by dimxy** [comment]
see issue #10 update https://github.com/KomodoPlatform/zebra/issues/10#issuecomment-1434261438 regarding this fix 73fb0cac68191a9ffc5c7b1ded23577908b1981f

**Comment by dimxy** [comment]
more tests enabled for komodo, added a test for the komodo_check_fork_is_valid() fix

**Review by DeckerSU — APPROVED** [review]
LGTM, as we have decided to merge all major changes into the `main` branch. However, additional and more comprehensive tests will need to be carried out before we can tag the `alpha` release.

**Comment by dimxy** [comment]
closes #7 #8 
partially implements #10

**Pull request merged**
